### ISSUE TITLE
error XA2002: Can not resolve reference in Android Project

### ISSUE THREAD

**Issue by PatGet** [sthewissen/Xamarin.Forms.DebugRainbows#11]
By just adding the NuGet to my Shared Project iget the following Error in my Android Project:

> C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1866,2): error XA2002: Can not resolve reference: `Xamarin.Forms.DebugRainbows`, referenced by `XYZ`. Please add a NuGet package or assembly reference for `Xamarin.Forms.DebugRainbows`, or remove the reference to `XYZ`.

If i add the Nuget to Android too it works. That should not be needed, right?

**Comment by sthewissen** [comment]
Indeed it shouldn't. There's no Android-specific code in there. A clean/rebuild/remove bin/obj didn't do the trick either?

**Comment by IoTFier** [comment]
Hi @sthewissen , I am facing the same error with v1.0.16 as well. 
A clean / rebuild / remove bin/obj didn't work.
