### ISSUE TITLE
[Feature] Make debug grid start from center

### ISSUE THREAD

**Issue by sthewissen** [sthewissen/Xamarin.Forms.DebugRainbows#21]
Add a property for the overlay grid to start from the horizontal and vertical center with a Major grid line (if used) and space itself out to the top, bottom, left and right. Probably best off making a property named `GridOrigin` with an enum containing `TopLeft` and `Center` for now. Can always add more if needed.

**Comment by adenearnshaw** [comment]
Perhaps there's two different ways to center the grid: by a single Major line thats centered; or by the square that two major grid lines make. E.g.

Major line Centered
![MainLine_Centered](https://user-images.githubusercontent.com/1441222/71597698-2c54ab80-2b3c-11ea-83ed-468ad48db984.png)

Major Grid Centered
![MainLinePair_Centered](https://user-images.githubusercontent.com/1441222/71597697-2c54ab80-2b3c-11ea-975b-08e03f4555c4.png)

**Comment by sthewissen** [comment]
Starting from the center with a line and moving it left and right outwards is the simple version. Got that implemented for the iOS version already :) Not quite sure about the calculations for the other one and how to approach that. I'll focus on the `Center` version first.

![image](https://user-images.githubusercontent.com/2419439/71598473-3334eb80-2b47-11ea-82ad-d880dce21284.png)

**Comment by sthewissen** [comment]
Will be in 1.1.4.
