### ISSUE TITLE
Sample code for DebugRainbows has a XAML typo

### ISSUE THREAD

**Issue by wyldebill** [sthewissen/Xamarin.Forms.DebugRainbows#22]
On this page, https://www.thewissen.io/a-quick-explainer-recent-nuget-packages/, the sample code to insert the DebugRainbows xaml has an extra space between the "clr-namespace:" and the "assembly=".  It's enough to make the XAML editor freak out and suggest a new namespace of DebugRainbows instead of "local".  It still compiles and runs with the extra space but for a newbie it could be confusing.

**Comment by sthewissen** [comment]
Fixed!
