### ISSUE TITLE
Read.me not updated or not synchroised with Release nuget

### ISSUE THREAD

**Issue by filipoff2** [sthewissen/Xamarin.Forms.DebugRainbows#24]
Read.me
<ResourceDictionary>
            <Style TargetType="ContentPage" ApplyToDerivedTypes="True">
               <**Setter Property="rainbows:DebugRainbow.ShowColors" Value="True" />**
            </Style>
</ResourceDictionary>

On nuget 1.0.16  I used and it worked 
<ResourceDictionary>
            <Style TargetType="ContentPage" ApplyToDerivedTypes="True">
                <**Setter Property="rainbows:DebugRainbow.IsDebug" Value="True" />**
            </Style>
</ResourceDictionary>

ShowColors is gone and IsDebug is accessible from XAML.

**Comment by filipoff2** [comment]
ok all The cool stuff is on pre version

**Comment by sthewissen** [comment]
Hey Bogusław, yeah those are currently in Beta. I think I'll push them into a release package soon though. I haven't heard any negative feedback coming back on the beta, so expect them in a PRD feed near you soon :)
