### ISSUE TITLE
Change description

### ISSUE THREAD

**Issue by Saccomani** [sthewissen/Xamarin.Forms.DebugRainbows#25]
the correct is rainbows:DebugRainbow.IsDebug="true" not rainbows:DebugRainbow.ShowColors="true"

**Comment by sthewissen** [comment]
Not anymore in the latest version of the package.

https://github.com/sthewissen/Xamarin.Forms.DebugRainbows/blob/master/src/Xamarin.Forms.DebugRainbows.Multi/Platforms/Shared/DebugRainbow.cs#L11
