### ISSUE TITLE
Forms 4 only?

### ISSUE THREAD

**Issue by MBrekhof** [sthewissen/Xamarin.Forms.DebugRainbows#6]
Am I correct in assuming that it is running on forms 4.xxx only?

**Comment by sthewissen** [comment]
It should not be. The library uses 3.5.0.129452.

**Comment by MBrekhof** [comment]
I got it running by copying the code, issue closed I think

**Comment by MBrekhof** [comment]
(btw, thanks!)

**Comment by sthewissen** [comment]
No problem, I didn't do much ;)

**Comment by hhuseyinpay** [comment]
Does the library support 4.xxx? Will it support?

**Comment by sthewissen** [comment]
I plan to upgrade all my packages soon. Just haven't gotten around to it.

**Comment by MBrekhof** [comment]
fwiw, we are running it in 4 without a problem
